url: http://www.mahfoudbennoune.com
sitename: 'Mahfoud Bennoune'
description: 'Tribute to the life and work of Mahfoud Bennoune, PhD, Algerian anthropologist, professor, scholar, activist and humanist.'
# do not include  https://github.com/...
default_author: "Bud Parr"

#Jekyll Options
# if using more than one Jekyll instance on your local machine
port: 4040
# paginate tells Jekyll how many posts per page
# paginate: 1
# Permalinks
permalink:  pretty
# Dependencies
#Pages - store all pages in the _pages directory
include: ['_pages']
relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile', 'Gemfile.lock','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'README.md', 'prose.yaml']
# gems:
#   - jekyll-sitemap


# dev options (true/false)
# if site is in production, 'production: true'
production: true
use_pure_css: false
use_jquery_cdn: true
include_font_awesome: false
include_addthis_sharing: false
bust_css_cache: false

# options (data)
google_analytics_id: UA-50141097-2
disqus_id:
addthis_id:
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:

# options (social)
# facebook_id:
twitter_id: budparr

# navigation options - effects layout/default. May also need options set in sass files
include_nav-top: false
include_nav-side-left: true
include_nav-side-right: false
